profile-packages-metadata/CustomObject/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profile-packages-metadata/CustomObject/objects/PriceBook__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price books</relationshipLabel>
        <relationshipName>Price_books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>new</fullName>
                </value>
                <value>
                    <fullName>sold</fullName>
                </value>
                <value>
                    <fullName>used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price book</label>
    <nameField>
        <label>Price book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

profile-packages-metadata/ApexClass/classes/PriceBookTriggerHandler.cls
public with sharing class PriceBookTriggerHandler {

	public static void setStatusUpdate(List<PriceBook__c> newPriceBooks, Map<Id, PriceBook__c> oldMapBooksByIds){
		for(PriceBook__c priceBook: newPriceBooks){
			if(oldMapBooksByIds.get(priceBook.Id).Account__r!=null && priceBook.Account__r==null){
				priceBook.addError('You can\'t delete existed Account');
			}else {
				if (oldMapBooksByIds.get(priceBook.Id).Account__r != null &&
						priceBook.Account__r != oldMapBooksByIds.get(priceBook.Id).Account__r) {
					priceBook.Status__c = 'used';
				} else if (oldMapBooksByIds.get(priceBook.Id).Account__r == null && priceBook.Account__r != null) {
					priceBook.Status__c = 'sold';
				}
			}
		}
	}
	public static void setStatusInsert(List<PriceBook__c> priceBooks){
		for(PriceBook__c priceBook: priceBooks){
			if(priceBook.Account__r==null){
				priceBook.Status__c='new';
			}else {
				priceBook.Status__c='sold';
			}
		}

	}
	public static void setAccountsInCars(List<PriceBook__c> priceBooks){
		Map<String, Id> mapIdsByModels = new Map<String, Id>();
		for(PriceBook__c priceBook: priceBooks){
			mapIdsByModels.put(priceBook.Model__c, priceBook.Account__c);
		}

		List<Car__c> cars = [
				SELECT Id, Account__c, Model__c
				FROM Car__c
				WHERE Model__c IN :mapIdsByModels.keySet()
		];

		for (Car__c car: cars) {
			car.Account__c = mapIdsByModels.get(car.Model__c);
		}

		Database.update(cars);
	}
}